// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsMvapBn5YVd7q170ng--FOx-Fp_YqEUg',
    appId: '1:852225593146:web:6016071c9577040cb74a03',
    messagingSenderId: '852225593146',
    projectId: 'projetoweb-54bbf',
    authDomain: 'projetoweb-54bbf.firebaseapp.com',
    storageBucket: 'projetoweb-54bbf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUcFW8pv_n5d-C5Sqfy75r2g_3aHqiGms',
    appId: '1:852225593146:android:917b79c915016e9cb74a03',
    messagingSenderId: '852225593146',
    projectId: 'projetoweb-54bbf',
    storageBucket: 'projetoweb-54bbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwjLijSpMkBSvZEWDcrLefeelInHmLhHc',
    appId: '1:852225593146:ios:7036e4d8993839a0b74a03',
    messagingSenderId: '852225593146',
    projectId: 'projetoweb-54bbf',
    storageBucket: 'projetoweb-54bbf.firebasestorage.app',
    iosBundleId: 'com.example.servicoamigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwjLijSpMkBSvZEWDcrLefeelInHmLhHc',
    appId: '1:852225593146:ios:7036e4d8993839a0b74a03',
    messagingSenderId: '852225593146',
    projectId: 'projetoweb-54bbf',
    storageBucket: 'projetoweb-54bbf.firebasestorage.app',
    iosBundleId: 'com.example.servicoamigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsMvapBn5YVd7q170ng--FOx-Fp_YqEUg',
    appId: '1:852225593146:web:28905dd898208742b74a03',
    messagingSenderId: '852225593146',
    projectId: 'projetoweb-54bbf',
    authDomain: 'projetoweb-54bbf.firebaseapp.com',
    storageBucket: 'projetoweb-54bbf.firebasestorage.app',
  );
}
